"""Regenerate the checked in schema files from the SQLAlchemy models.

    python scripts/generate_schema.py

The application creates the schema by itself on startup, these files exist for people who
pre-create the database with a DBA account.
"""

import sys
from pathlib import Path

from sqlalchemy import create_mock_engine

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from vulncano.models import Base  # noqa: E402

DIALECTS = {"mysql": "mysql+pymysql://", "sqlite": "sqlite://"}
HEADER = "-- Generated by scripts/generate_schema.py, do not edit by hand.\n"


def render(dialect_url: str) -> str:
    statements = []
    engine = create_mock_engine(dialect_url, lambda sql, *args, **kwargs: statements.append(
        str(sql.compile(dialect=engine.dialect)).strip()
    ))
    Base.metadata.create_all(engine, checkfirst=False)
    body = ";\n\n".join(
        statement.replace("CREATE TABLE ", "CREATE TABLE IF NOT EXISTS ", 1)
        if statement.startswith("CREATE TABLE ") else statement
        for statement in statements
    )
    return HEADER + body + ";\n"


for name, url in DIALECTS.items():
    target = ROOT / "scripts" / f"schema.{name}.sql"
    target.write_text(render(url))
    print(f"wrote {target.relative_to(ROOT)}")
