-- Generated by scripts/generate_schema.py, do not edit by hand.
CREATE TABLE IF NOT EXISTS counters (
	name VARCHAR(32) NOT NULL, 
	value INTEGER NOT NULL, 
	PRIMARY KEY (name)
);

CREATE TABLE IF NOT EXISTS projects (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	`key` VARCHAR(32) NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	description TEXT NOT NULL, 
	sla_critical INTEGER NOT NULL, 
	sla_high INTEGER NOT NULL, 
	sla_medium INTEGER NOT NULL, 
	sla_low INTEGER NOT NULL, 
	sla_info INTEGER NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (`key`)
);

CREATE TABLE IF NOT EXISTS report_jobs (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	status VARCHAR(16) NOT NULL, 
	template VARCHAR(120) NOT NULL, 
	output_format VARCHAR(8) NOT NULL, 
	params TEXT NOT NULL, 
	finding_ids TEXT NOT NULL, 
	output_path VARCHAR(500) NOT NULL, 
	bundle_path VARCHAR(500) NOT NULL, 
	error TEXT NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	finished_at DATETIME, 
	PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS plans (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	ref VARCHAR(16) NOT NULL, 
	project_id INTEGER NOT NULL, 
	name VARCHAR(200) NOT NULL, 
	target_version VARCHAR(120) NOT NULL, 
	target_date DATE, 
	owner VARCHAR(120) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	notes TEXT NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (ref), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX ix_plans_project_id ON plans (project_id);

CREATE TABLE IF NOT EXISTS cvss_project_config (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	project_id INTEGER NOT NULL, 
	`E` VARCHAR(2) NOT NULL, 
	`RL` VARCHAR(2) NOT NULL, 
	`RC` VARCHAR(2) NOT NULL, 
	`CR` VARCHAR(2) NOT NULL, 
	`IR` VARCHAR(2) NOT NULL, 
	`AR` VARCHAR(2) NOT NULL, 
	`MAV` VARCHAR(2) NOT NULL, 
	`MAC` VARCHAR(2) NOT NULL, 
	`MPR` VARCHAR(2) NOT NULL, 
	`MUI` VARCHAR(2) NOT NULL, 
	`MS` VARCHAR(2) NOT NULL, 
	`MC` VARCHAR(2) NOT NULL, 
	`MI` VARCHAR(2) NOT NULL, 
	`MA` VARCHAR(2) NOT NULL, 
	PRIMARY KEY (id), 
	UNIQUE (project_id), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS scanner_configs (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	project_id INTEGER, 
	tool VARCHAR(40) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	enabled BOOL NOT NULL, 
	config_enc TEXT NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_scanner_project_name UNIQUE (project_id, name), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX ix_scanner_configs_project_id ON scanner_configs (project_id);

CREATE TABLE IF NOT EXISTS api_tokens (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	name VARCHAR(120) NOT NULL, 
	project_id INTEGER, 
	prefix VARCHAR(16) NOT NULL, 
	token_hash VARCHAR(64) NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	last_used_at DATETIME, 
	revoked_at DATETIME, 
	PRIMARY KEY (id), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, 
	UNIQUE (token_hash)
);

CREATE TABLE IF NOT EXISTS scans (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	ref VARCHAR(16) NOT NULL, 
	project_id INTEGER NOT NULL, 
	scanner_config_id INTEGER, 
	tool VARCHAR(40) NOT NULL, 
	source VARCHAR(500) NOT NULL, 
	status VARCHAR(16) NOT NULL, 
	remote_id VARCHAR(200) NOT NULL, 
	raw_path VARCHAR(500) NOT NULL, 
	parsed_json TEXT NOT NULL, 
	log TEXT NOT NULL, 
	error TEXT NOT NULL, 
	parsed_count INTEGER NOT NULL, 
	imported_count INTEGER NOT NULL, 
	started_at DATETIME, 
	finished_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (ref), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(scanner_config_id) REFERENCES scanner_configs (id) ON DELETE SET NULL
);

CREATE INDEX ix_scans_project_id ON scans (project_id);

CREATE INDEX ix_scans_status ON scans (status);

CREATE TABLE IF NOT EXISTS findings (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	ref VARCHAR(16) NOT NULL, 
	project_id INTEGER NOT NULL, 
	cve_id VARCHAR(32), 
	external_id VARCHAR(120) NOT NULL, 
	title VARCHAR(500) NOT NULL, 
	description TEXT NOT NULL, 
	cve_pub_date DATE, 
	severity VARCHAR(16) NOT NULL, 
	components TEXT NOT NULL, 
	scan_type VARCHAR(16) NOT NULL, 
	tool VARCHAR(40) NOT NULL, 
	origin VARCHAR(120) NOT NULL, 
	status VARCHAR(20) NOT NULL, 
	mitigation TEXT NOT NULL, 
	file_path VARCHAR(500) NOT NULL, 
	line INTEGER, 
	reported BOOL NOT NULL, 
	cvss_vector VARCHAR(200) NOT NULL, 
	cvss_base_score FLOAT, 
	cvss_source VARCHAR(40) NOT NULL, 
	cvss_fetched_at DATETIME, 
	adapted_score FLOAT, 
	adapted_vector VARCHAR(400) NOT NULL, 
	scan_id INTEGER, 
	regressed_at DATETIME, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	updated_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (ref), 
	FOREIGN KEY(project_id) REFERENCES projects (id) ON DELETE CASCADE, 
	FOREIGN KEY(scan_id) REFERENCES scans (id) ON DELETE SET NULL
);

CREATE INDEX ix_findings_cve_id ON findings (cve_id);

CREATE INDEX ix_findings_severity ON findings (severity);

CREATE INDEX ix_findings_tool ON findings (tool);

CREATE INDEX ix_findings_scan_type ON findings (scan_type);

CREATE INDEX ix_findings_project_id ON findings (project_id);

CREATE INDEX ix_findings_status ON findings (status);

CREATE TABLE IF NOT EXISTS patches (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	ref VARCHAR(16) NOT NULL, 
	finding_id INTEGER NOT NULL, 
	plan_id INTEGER, 
	fixed_version VARCHAR(120) NOT NULL, 
	patch_pub_date DATE, 
	functional_impact TEXT NOT NULL, 
	operational_impact TEXT NOT NULL, 
	regression_tests TEXT NOT NULL, 
	schedule VARCHAR(200) NOT NULL, 
	applied_at DATE, 
	comments TEXT NOT NULL, 
	created_at DATETIME NOT NULL DEFAULT now(), 
	PRIMARY KEY (id), 
	UNIQUE (ref), 
	UNIQUE (finding_id), 
	FOREIGN KEY(finding_id) REFERENCES findings (id) ON DELETE CASCADE, 
	FOREIGN KEY(plan_id) REFERENCES plans (id) ON DELETE SET NULL
);

CREATE INDEX ix_patches_plan_id ON patches (plan_id);

CREATE TABLE IF NOT EXISTS cvss_finding_overrides (
	id INTEGER NOT NULL AUTO_INCREMENT, 
	finding_id INTEGER NOT NULL, 
	`E` VARCHAR(2), 
	`RL` VARCHAR(2), 
	`RC` VARCHAR(2), 
	`CR` VARCHAR(2), 
	`IR` VARCHAR(2), 
	`AR` VARCHAR(2), 
	`MAV` VARCHAR(2), 
	`MAC` VARCHAR(2), 
	`MPR` VARCHAR(2), 
	`MUI` VARCHAR(2), 
	`MS` VARCHAR(2), 
	`MC` VARCHAR(2), 
	`MI` VARCHAR(2), 
	`MA` VARCHAR(2), 
	PRIMARY KEY (id), 
	UNIQUE (finding_id), 
	FOREIGN KEY(finding_id) REFERENCES findings (id) ON DELETE CASCADE
);
